# Generated by Django 5.2.12 on 2026-03-17 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='address',
            name='company_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='profile',
            name='anonymous_packaging',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='marketing_opt_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_currency',
            field=models.CharField(default='EUR', max_length=3),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='privacy_mode_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
